### ISSUE TITLE
Override method in report_webkit

### ISSUE THREAD

**Issue by ovnicraft** [OCA/OCB#285]
Hi, i am trying to override [create_single_pdf](https://github.com/OCA/OCB/blob/7.0/addons/report_webkit/webkit_report.py#L197) method and [create](https://github.com/OCA/OCB/blob/7.0/addons/report_webkit/webkit_report.py#L310) method from report_webkit module.

So my code: https://gist.github.com/ovnicraft/c6cb99cf0a99f1d718bf

but never run my code, any hint around ?

**Comment by gdgellatly** [comment]
The class name is misleading.  WebkitParser isn't really a parser in the
traditional reporting sense (as you can see the init method takes its own
parser arg), rather a reporting method.  So while you create a new class it
never gets instantiated anywhere.

So there are a few ways depending on what you want to do but the best way
is number 1.
1. Optionally create a new report type say webkit_signed if it only applies
   to some reports, then overide _lookup_report to use the new parser for
   reports of that type in ir.actions.report.xml.  To apply to all reports
   then you could still do 1 and ensure the MRO picks your _lookup_report
   function first, which it should if it inherits from report_webkit module.

Or if you want to monkey patch and apply to all webkit reports then it gets
a bit ugly but something like below pseudocode would probably work.  Given
you can rely on the ir.actions inheritance I probably wouldn't do this but
sometimes it is really necessary.

import openerp.addons. ... webkit_parser

create_parent = openerp.addons. ... webkit_parser.create

def create(args)

  res = create_parent(args) # instead of super

def sign(args)

  code

openerp.addons. ... webkit_parser.create = create

openerp.addons. ... webkit_parser.sign = sign

although Sent from TypeMail http://www.typeapp.com/r

**Comment by ovnicraft** [comment]
I found the solution overriding register_report function, totally a dirty hack.
