### ISSUE TITLE
Coveralls to OCB branch

### ISSUE THREAD

**Issue by danimaribeiro** [OCA/OCB#340]
Can we have coveralls configured in OCB branch ?

I'd like to create unit tests for Odoo, it'll help to see where we need to create tests.

**Comment by pedrobaeza** [comment]
The coverage is already done, but it's not shown on README: https://coveralls.io/github/OCA/OCB.

**Comment by danimaribeiro** [comment]
Nice one.

Is the OCB branch accept PR tests?

**Comment by pedrobaeza** [comment]
You must propose them to Odoo also, but you can use OCB coveralls to see how the coverage improves.

**Comment by danimaribeiro** [comment]
I did, but probably no one will answer there :/
https://github.com/odoo/odoo/issues/8878

I'll close this one, thanks.

**Comment by pedrobaeza** [comment]
I'm talking about proposing tests to Odoo also, not the coveralls thing. Odoo has another development cycle, and they don't have coveralls in it, so it's logical not to accept it. Your workflow can be:
- Develop tests
- Propose them on Odoo
- Propose them also on OCB and see there the coverage increase.
- If Odoo doesn't accept them, there's a chance to be accepted on OCB, because they don't modify the DB layout.
- Later, if a bug is discovered thanks to these tests, we can go to Odoo saying that the test has discovered it.

**Comment by danimaribeiro** [comment]
Ah, ok.
I'll do this flow.
:+1:
