### ISSUE TITLE
[8.0] 'context' is not defined on loading account/account_view.xml

### ISSUE THREAD

**Issue by syci** [OCA/OCB#443]
I run a update=all and view this error:

openerp.tools.convert: Context value ({'search_default_account_id': [active_id], 'fiscalyear': context.get('fiscalyear')}) for element with id "action_account_items" or its data node does not parse at server-side, keeping original string, in case it's meant for client side only
Traceback (most recent call last):
  File "/home/mario/odoo/OCB/openerp/tools/convert.py", line 258, in get_context
    ctx_res = unsafe_eval(ctx, eval_dict)
  File "<string>", line 1, in <module>
NameError: name 'context' is not defined

**Comment by StefanRijnhart** [comment]
Hi @syci,

you are absolutely right, this is an infamous message during a database update. However, this is the OCB project and we accept bug reports that are caused by OCB specific changes. As the code is present in Odoo itself (https://github.com/odoo/odoo/blob/8.0/addons/account/account_view.xml#L355) I assume that this is not an OCB specific issue and you should report this on https://github.com/odoo/odoo _unless_ you have a fix that you want to propose into OCB. In that case, please file a pull request.
