### ISSUE TITLE
[9.0] Native upgrade mechanism in OCB, the Drupal way

### ISSUE THREAD

**Issue by ghost** [OCA/OCB#485]
Impacted versions: 9 and onwards

It is currently very hard to upgrade OCB from one major version to another. OpenUpgrade can do the job, but it is not very optimal. OpenUpgrade is complicated, unreliable and has thousands of lines of code (even if it is the only solution available and we like it).

Other major software, like Drupal, have solved this years ago.  Drupal has a native upgrade mechanism in each module:

In each module, a property returns major and minor version numbers. Then another property is able to display the needed SQL code to upgrade the module from one version to another. Yes, Drupal has dependencies and thanks to them, it is also very easy to upgrade and verify that the needed dependencies are available. I see nothing wrong in dependencies. As such, each Drupal module has a dependency to core.

In some situations, I was able to upgrade a 3 year old website with dozens of modules and click upgrade, which would trigger hundreds of SQL queries and in the end, Drupal is up to date.

Very little code is needed to do the job.

Now that there is a free community, it may be interesting to study HOW other communities manage upgrade. You are not going to convince a large company with million euros in support and development if you cannot upgrade the ERP. This is ridiculous. The current business model is "Come on it, the ERP is free, has thousands of modules, online versions, blabla". But do people really understand they are trapped needed the help of specialists and developers to upgrade or migrate? There is something wrong in the idea of trapping people to being stuck to a software version. What happens to a company after 10 years of hosting or using the same version of the ERP?

Drupal also has a very nice website, where all modules can be downloaded and still the community is free, without the need of a third party company.

This is the future, so let's study the way Drupal allows to manage, install, develop, upgrade and support thousands of modules. 

Kind regards,
Kellogs

**Comment by StefanRijnhart** [comment]
As well as https://github.com/OCA/OCB/issues/487, this is out of scope for OCB but should a fork become reality, this is the way to manage migrations of course. Closing this issue here though.

**Comment by dreispt** [comment]
@kellogs I confess I'm far from being an OpenUpgrade expert, but AFAIK the way Odoo upgrades work is very similar to what you describe. The mechanism is mostly there, what is missing are the migration scripts inside each core module. They exist but are kept private by the software editor, as a commercial strategy.
OpenUpgrades mission is to provide equivalent scripts built by the community.
Other community modules, such as the ones hosted by the OCA, can also have those scripts. 
AFAICS in the majority of cases they are not needed, since it's rare to have relevant data model changes, and their upgrade should be smooth. And in the cases I've seen where there are relevant data model changes, the necessary data structure conversion upon upgrade was provided by the module.

**Comment by StefanRijnhart** [comment]
@dreispt yes but there is truth in @kellogs' reasoning: in case of a proper fork we can simply include atomic migration scripts with each change together with the change itself instead.
