### ISSUE TITLE
user_id redeclared in account_move.py

### ISSUE THREAD

**Issue by ezerouali** [OCA/OCB#912]
Impacted versions: 13.0

Steps to reproduce: code weirdness

Current behavior: user_id field is declared twice, with nearly same data apart from help declaration property

Expected behavior: use only one declaration, most probably the second one.

Video/Screenshot link (optional):

line code 121 and line code 187

**Comment by pedrobaeza** [comment]
Hi, Ismael, several things:

- These issues shouldn't go here, but on odoo/odoo, as this is not specific of OCB, but of all Odoo.
- Any way, this is not an issue at all. Indeed the declaration can be duplicated, but that doesn't mean it doesn't work. The last one is the one used at all. And this kind of change can't be done in stable due to stability policy. Check if in master version, this is still happening, and if so, you can report it there.
