### ISSUE TITLE
[IMP] OCA modules name, summary and description not translatable

### ISSUE THREAD

**Issue by primes2h** [OCA/OCB#929]
Impacted versions:
All

Steps to reproduce:
Using an Odoo CE + OCA modules instance, change the system language, then go to Apps.
 
Current behavior:
Odoo CE apps name, summary, description are translated, OCA ones are not (still in English).
In fact "name", "summary" and "description" from manifest file are not translatable 

![image](https://user-images.githubusercontent.com/227940/82052801-88b80200-96bc-11ea-802a-74c7e112f0fc.png)

Expected behavior:
OCA modules name, summary and description to be translatable, showing up on Apps in the choosed language.

Insights
----------

Odoo uses "base" module to automatically extract those strings and put in the base.pot file. 

It does the trick parsing all available modules available in the instance (all repository added in the addons variable), extracting "name", "summary" and "description"/"readme" strings, and putting them on base.pot file.

So, in a standard Odoo CE installation, .pot file of "base" module contains only strings from all odoo standard modules. (the .pot you find on transifex).

But if you extract  "base" .pot with OCA repositories added on odoo.conf file
(Settings → Translations → Export Translation → App to export: Base)
it'll contain also strings from the new available OCA modules (name, summary, description and readme).

It shouldn't be too much complicated to integrate it in OCA/weblate flow. 
We just need to extract "base" .pot from a runbot  OCB instance with all OCA repos added.

Then, this .pot can be added on weblate, as well as  .po files (that contain strings translated from Transifex)

What do you think?

**Comment by pedrobaeza** [comment]
I'm afraid this is not possible due to a lot of reasons. Let me expose some of them:

- OCB is not hosting translations, so Weblate can't contain these translations, that will be a mix between Odoo terms and these extra modules manifests.
- Even doing that, continuous merge conflicts will arise when we merge automatically upstream code.
- Install all OCA modules together is impossible, as there are for sure incompatibilities between them (some of them already known and done on purpose).
- Even also if feasible technically, it's not possible to each time any move is done on any of the ~200 OCA repositories, to be reflected in this mega-instance due to server resources.

The solution must come from other way: Odoo supporting this natively, or at OCA level through its Apps Gallery showing it translated.

For the first one, it has been arisen several times in Odoo, and the last one is https://github.com/odoo/odoo/issues/47334.

For the OCA part, something similar to my proposal in previous issue can be considered (having a README.lang.rst file in the OCA module root), and being parsed in the apps gallery for showing depending on the visitor language.

@OCA/board of you interest.

**Comment by primes2h** [comment]
@pedrobaeza 
Thanks a lot for the nice clarification.
In some way it's a real showstopper bug for translation integration flow, it's a pity Odoo is not keen on fixing it.

> For the OCA part, something similar to my proposal in previous issue can be considered (having a README..rst file in the OCA module root), and being parsed in the apps gallery for showing depending on the visitor language.

But this needs a fix on Odoo side as well, am I wrong?

**Comment by pedrobaeza** [comment]
Not really, as we control that Apps Gallery. I'm talking about https://odoo-community.org/shop.

The involved modules are in https://github.com/OCA/apps-store

**Comment by primes2h** [comment]
> Not really, as we control that Apps Gallery. I'm talking about https://odoo-community.org/shop.

Ok, this would be really nice but it won't fix the original issue of not having module name/description translated on Odoo itself. :disappointed:

> The involved modules are in https://github.com/OCA/apps-store

Thanks a lot for pointing me up, I'll give it a look.

**Comment by primes2h** [comment]
@pedrobaeza 
Just some thoughts and clarification about your reply.

> I'm afraid this is not possible due to a lot of reasons. Let me expose some of them:
> 
>     * OCB is not hosting translations, so Weblate can't contain these translations, that will be a mix between Odoo terms and these extra modules manifests.

In fact it would be just a base.pot file and corresponding *.po files. 
 
>     * Even doing that, continuous merge conflicts will arise when we merge automatically upstream code.

This is true.
Maybe this could be handled by some script using msgmerge, I need to deepen it.

>     * Install all OCA modules together is impossible, as there are for sure incompatibilities between them (some of them already known and done on purpose).

No, you don't need OCA modules to be "installed" to make it work.
You just need a base Odoo CE instance with OCA repos "available", so added in addons_path.
If you extract base.pot from this setup it'll contain all extra strings from OCA modules.

 
>     * Even also if feasible technically, it's not possible to each time any move is done on any of the ~200 OCA repositories, to be reflected in this mega-instance due to server resources.

As stated above, no mega-instance required, just a base one.

**Comment by pedrobaeza** [comment]
You need any way to maintain that environment that has all the repositories cloned and available in addons path, and be refreshed each time. As said, this is not going feasible to be done while no other option at core level is presented.
